import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "picsum.photos" },
      { protocol: "https", hostname: "static01.nyt.com" },
      { protocol: "https", hostname: "www.nyt.com" },
      { protocol: "https", hostname: "ichef.bbci.co.uk" },
      { protocol: "https", hostname: "nav.files.bbci.co.uk" },
      { protocol: "https", hostname: "images.mktw.net" },
      { protocol: "https", hostname: "image.cnbcfm.com" },
      { protocol: "https", hostname: "media.zenfs.com" },
      { protocol: "https", hostname: "cloudfront-us-east-1.images.arcpublishing.com" },
      { protocol: "https", hostname: "s.yimg.com" },
      { protocol: "https", hostname: "cdn.i-scmp.com" },
      { protocol: "https", hostname: "www.engadget.com" },
      { protocol: "https", hostname: "techcrunch.com" },
      { protocol: "https", hostname: "venturebeat.com" },
      { protocol: "https", hostname: "arstechnica.com" },
      { protocol: "https", hostname: "cdn.arstechnica.net" },
      { protocol: "https", hostname: "media.wired.com" },
      { protocol: "https", hostname: "spectrum.ieee.org" },
      { protocol: "https", hostname: "www.newscientist.com" },
      { protocol: "https", hostname: "cloudfront-us-east-1.arcpublishing.com" },
      { protocol: "https", hostname: "hips.hearstapps.com" },
      { protocol: "https", hostname: "www.caranddriver.com" },
      { protocol: "https", hostname: "www.motortrend.com" },
      { protocol: "https", hostname: "www.autoblog.com" },
      { protocol: "https", hostname: "electrek.co" },
      { protocol: "https", hostname: "cdn.mos.cms.futurecdn.net" },
      { protocol: "https", hostname: "media-assets.wired.com" },
      { protocol: "https", hostname: "images.adsttc.com" },
      { protocol: "https", hostname: "robbreport.com" },
      { protocol: "https", hostname: "www.cnet.com" },
      { protocol: "https", hostname: "www.zdnet.com" },
      { protocol: "https", hostname: "www.tomsguide.com" },
      { protocol: "https", hostname: "www.digitaltrends.com" },
      { protocol: "https", hostname: "i.kinja-img.com" },
      { protocol: "https", hostname: "gizmodo.com" },
      { protocol: "https", hostname: "thenextweb.com" },
      { protocol: "https", hostname: "futurism.com" },
      { protocol: "https", hostname: "www.science.org" },
      { protocol: "https", hostname: "www.nasa.gov" },
      { protocol: "https", hostname: "images-assets.nasa.gov" },
      { protocol: "https", hostname: "www.washingtonpost.com" },
      { protocol: "https", hostname: "thumbor.thedailymeal.com" },
      { protocol: "https", hostname: "www.twincities.com" },
      { protocol: "https", hostname: "content.api.news" },
      { protocol: "https", hostname: "prod.static9.net.au" },
    ],
  },
};

export default nextConfig;
