import { Article } from './types';

const now = Date.now();
const min = 60 * 1000;
const hr = 60 * min;

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'OpenAI Unveils GPT-5 with Breakthrough Reasoning Capabilities',
    summary: 'The latest model demonstrates unprecedented performance on complex multi-step reasoning tasks.',
    fullContent: 'OpenAI has announced GPT-5, their most advanced language model to date. The model features a new architecture that enables significantly improved reasoning capabilities.',
    source: 'TechCrunch',
    sourceLogo: '⚡',
    category: 'ai',
    imageUrl: 'https://picsum.photos/seed/gpt5/800/450',
    publishedAt: new Date(now - 2 * min).toISOString(),
    url: '#',
    isLive: true,
    isNew: true,
    isExpired: false,
  },
  {
    id: '2',
    title: 'Global Markets Rally as Trade Tensions Ease',
    summary: 'Stock indices surge worldwide after breakthrough diplomatic talks.',
    fullContent: 'Global financial markets experienced a significant rally today following new trade agreements.',
    source: 'Bloomberg',
    sourceLogo: '📊',
    category: 'trading',
    imageUrl: 'https://picsum.photos/seed/markets/800/450',
    publishedAt: new Date(now - 15 * min).toISOString(),
    url: '#',
    isLive: false,
    isNew: true,
    isExpired: false,
  },
  {
    id: '3',
    title: 'SpaceX Successfully Lands Starship After Orbital Flight',
    summary: 'The fully reusable rocket completed a full orbit before executing a precision landing.',
    fullContent: 'SpaceX achieved another historic milestone today as Starship completed its first full orbital flight.',
    source: 'Ars Technica',
    sourceLogo: '🚀',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/spacex/800/450',
    publishedAt: new Date(now - 45 * min).toISOString(),
    url: '#',
    isLive: true,
    isNew: false,
    isExpired: false,
  },
  {
    id: '4',
    title: 'Apple Announces Revolutionary Mixed Reality Headset',
    summary: 'The new device blends digital content with the real world.',
    fullContent: 'Apple unveiled its next-generation mixed reality headset at WWDC.',
    source: 'The Verge',
    sourceLogo: '🍎',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/apple-mr/800/450',
    publishedAt: new Date(now - 4 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
    isExpired: false,
  },
  {
    id: '5',
    title: 'Ceasefire Negotiations Resume After Intense Fighting',
    summary: 'Diplomats from both sides meet for fresh talks.',
    fullContent: 'Representatives from both nations have gathered for renewed ceasefire negotiations.',
    source: 'Al Jazeera',
    sourceLogo: '🕊️',
    category: 'wars',
    imageUrl: 'https://picsum.photos/seed/ceasefire/800/450',
    publishedAt: new Date(now - 30 * min).toISOString(),
    url: '#',
    isLive: true,
    isNew: true,
    isExpired: false,
  },
  {
    id: '6',
    title: 'EU Parliament Passes Sweeping AI Regulation Framework',
    summary: 'The new legislation establishes strict guidelines for AI deployment.',
    fullContent: 'The EU has passed its landmark AI Act.',
    source: 'Reuters',
    sourceLogo: '🏛️',
    category: 'ai',
    imageUrl: 'https://picsum.photos/seed/eu-ai/800/450',
    publishedAt: new Date(now - 3 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
    isExpired: false,
  },
  {
    id: '7',
    title: 'Tesla Unveils Affordable $25,000 Electric Vehicle',
    summary: 'The new compact EV aims to make electric transportation accessible.',
    fullContent: 'Tesla has officially revealed its highly anticipated $25,000 electric vehicle.',
    source: 'Electrek',
    sourceLogo: '🚗',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/tesla/800/450',
    publishedAt: new Date(now - 16 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
    isExpired: false,
  },
  {
    id: '8',
    title: 'Quantum Computer Achieves Error Correction Milestone',
    summary: 'IBM demonstrates fault-tolerant computation at scale.',
    fullContent: 'IBM announced a major breakthrough in quantum computing.',
    source: 'MIT Tech Review',
    sourceLogo: '💻',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/quantum/800/450',
    publishedAt: new Date(now - 1 * 24 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
    isExpired: true,
  },
  {
    id: '9',
    title: 'Major Cybersecurity Breach Exposes 200M Users',
    summary: 'A sophisticated attack on a cloud provider.',
    fullContent: 'A major cybersecurity incident has exposed personal data.',
    source: 'Wired',
    sourceLogo: '🔒',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/cyber/800/450',
    publishedAt: new Date(now - 6 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
    isExpired: false,
  },
  {
    id: '10',
    title: 'UN Peacekeepers Deployed in Central Africa',
    summary: 'A new multinational force arrives.',
    fullContent: 'The UN has deployed 5,000 peacekeepers.',
    source: 'Reuters',
    sourceLogo: '🏛️',
    category: 'wars',
    imageUrl: 'https://picsum.photos/seed/peacekeepers/800/450',
    publishedAt: new Date(now - 3 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
    isExpired: false,
  },
  {
    id: '11',
    title: 'Meta Unveils AI Image Generator Rivaling DALL-E',
    summary: 'The new model creates photorealistic images from text.',
    fullContent: 'Meta released a new AI image generation model.',
    source: 'NY Times',
    sourceLogo: '📰',
    category: 'ai',
    imageUrl: 'https://picsum.photos/seed/meta-ai/800/450',
    publishedAt: new Date(now - 5 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
    isExpired: false,
  },
  {
    id: '12',
    title: 'South China Sea Dispute Escalation Warning',
    summary: 'Naval deployments increase amid territorial claims.',
    fullContent: 'Defense analysts are raising concerns about an escalation.',
    source: 'Defense One',
    sourceLogo: '⚓',
    category: 'wars',
    imageUrl: 'https://picsum.photos/seed/naval/800/450',
    publishedAt: new Date(now - 6 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
    isExpired: false,
  },
];

export const trendingTopics = [
  { topic: 'S&P 500', count: '+1.2% today' },
  { topic: 'NVIDIA', count: '$180.50' },
  { topic: 'Bitcoin', count: '$68,420' },
  { topic: 'Gold', count: '$2,380/oz' },
  { topic: 'Tesla (TSLA)', count: '$252.30' },
];

export const topSources = [
  { name: 'CNBC', articles: 342, logo: '/logos/cnbc.svg' },
  { name: 'MarketWatch', articles: 289, logo: '/logos/marketwatch.svg' },
  { name: 'Bloomberg', articles: 256, logo: '/logos/cnbc.svg' },
  { name: 'NY Times Business', articles: 231, logo: '/logos/nyt.svg' },
  { name: 'Reuters Finance', articles: 198, logo: '/logos/cnbc.svg' },
];
