import { Article } from './types';

const now = Date.now();
const min = 60 * 1000;
const hr = 60 * min;

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'OpenAI Unveils GPT-5 with Breakthrough Reasoning Capabilities',
    summary: 'The latest model demonstrates unprecedented performance on complex multi-step reasoning tasks, surpassing human experts in several benchmarks.',
    fullContent: 'OpenAI has announced GPT-5, their most advanced language model to date. The model features a new architecture that enables significantly improved reasoning capabilities, particularly in mathematics, coding, and scientific analysis. Early benchmarks show it outperforming human experts in complex multi-step reasoning tasks. The model is expected to roll out to ChatGPT Plus users within the coming weeks, with API access following shortly after. Industry experts say this represents a significant leap forward in AI capabilities.',
    source: 'TechCrunch',
    sourceLogo: '⚡',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/gpt5/800/450',
    publishedAt: new Date(now - 2 * min).toISOString(),
    url: '#',
    isLive: true,
    isNew: true,
  },
  {
    id: '2',
    title: 'Global Markets Rally as Trade Tensions Ease Between Major Economies',
    summary: 'Stock indices surge worldwide after breakthrough diplomatic talks signal a new era of economic cooperation.',
    fullContent: 'Global financial markets experienced a significant rally today following the announcement of new trade agreements between major world economies. The S&P 500 gained 2.3%, while European and Asian markets showed similar gains. Analysts attribute the surge to optimism surrounding reduced tariffs and simplified regulatory frameworks. The Dow Jones Industrial Average jumped over 500 points in early trading, marking one of the best days of the year.',
    source: 'Bloomberg',
    sourceLogo: '📊',
    category: 'business',
    imageUrl: 'https://picsum.photos/seed/markets/800/450',
    publishedAt: new Date(now - 15 * min).toISOString(),
    url: '#',
    isLive: false,
    isNew: true,
  },
  {
    id: '3',
    title: 'SpaceX Successfully Lands Starship After Orbital Flight Test',
    summary: 'The fully reusable rocket completed a full orbit before executing a precision landing at the Boca Chica facility.',
    fullContent: 'SpaceX achieved another historic milestone today as Starship completed its first full orbital flight and successfully landed back at the launch site. The mission lasted approximately 90 minutes, during which the vehicle reached an altitude of 250 kilometers before beginning its descent. Elon Musk confirmed that the next test flight is already being planned for next month.',
    source: 'Ars Technica',
    sourceLogo: '🚀',
    category: 'science',
    imageUrl: 'https://picsum.photos/seed/spacex/800/450',
    publishedAt: new Date(now - 45 * min).toISOString(),
    url: '#',
    isLive: true,
    isNew: false,
  },
  {
    id: '4',
    title: 'NBA Finals: Celtics Take 3-1 Lead After Dramatic Overtime Victory',
    summary: 'A clutch three-pointer with 0.8 seconds remaining sealed an incredible comeback for Boston.',
    fullContent: 'The Boston Celtics now stand just one win away from the championship after a thrilling overtime victory in Game 4 of the NBA Finals. Jayson Tatum scored 41 points, including the game-winning three-pointer. The game saw 14 lead changes and was tied 7 times in the fourth quarter alone.',
    source: 'ESPN',
    sourceLogo: '🏀',
    category: 'sports',
    imageUrl: 'https://picsum.photos/seed/nba/800/450',
    publishedAt: new Date(now - 2 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '5',
    title: 'EU Parliament Passes Sweeping AI Regulation Framework',
    summary: 'The new legislation establishes strict guidelines for AI deployment across member states, with heavy penalties for non-compliance.',
    fullContent: 'The European Union has passed its landmark AI Act, creating the most comprehensive regulatory framework for artificial intelligence in the world. The legislation classifies AI systems by risk level and imposes strict requirements on high-risk applications. Companies face fines of up to 7% of global revenue for violations. The law takes effect in 18 months.',
    source: 'Reuters',
    sourceLogo: '🏛️',
    category: 'world',
    imageUrl: 'https://picsum.photos/seed/eu-ai/800/450',
    publishedAt: new Date(now - 3 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '6',
    title: 'Apple Announces Revolutionary Mixed Reality Headset at WWDC',
    summary: 'The new device blends digital content with the real world using advanced spatial computing technology.',
    fullContent: 'Apple unveiled its next-generation mixed reality headset at the Worldwide Developers Conference, featuring breakthrough display technology and intuitive hand-tracking controls. The device runs on a custom M4 chip and offers an immersive experience that seamlessly blends digital content with the physical environment.',
    source: 'The Verge',
    sourceLogo: '🍎',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/apple-mr/800/450',
    publishedAt: new Date(now - 4 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '7',
    title: 'Researchers Discover New Species of Deep-Sea Creatures in Pacific Trench',
    summary: 'A team of marine biologists has documented over 30 previously unknown species living at extreme depths.',
    fullContent: 'Scientists from the Schmidt Ocean Institute have discovered more than 30 new species during an expedition to the Mariana Trench. The findings include bioluminescent organisms that thrive in complete darkness and pressures exceeding 1,000 atmospheres. The discovery could reshape our understanding of extremophile biology.',
    source: 'Nature',
    sourceLogo: '🔬',
    category: 'science',
    imageUrl: 'https://picsum.photos/seed/deepsea/800/450',
    publishedAt: new Date(now - 5 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '8',
    title: 'Major Cybersecurity Breach Exposes Data of 200 Million Users',
    summary: 'A sophisticated attack on a leading cloud provider has compromised personal information across multiple platforms.',
    fullContent: 'A major cybersecurity incident has exposed the personal data of approximately 200 million users across several popular online services. The attack targeted a widely-used cloud infrastructure provider and has prompted emergency security reviews across the tech industry. Affected companies are notifying users and resetting access credentials as a precaution.',
    source: 'Wired',
    sourceLogo: '🔒',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/cyber/800/450',
    publishedAt: new Date(now - 6 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '9',
    title: 'Champions League Final: Real Madrid Claims Record 16th Title',
    summary: 'A stunning second-half comeback sealed another European crown for the Spanish giants.',
    fullContent: 'Real Madrid has won the Champions League for a record-extending 16th time after coming from behind to beat Manchester City 3-1 in the final. Vinícius Jr. scored twice in the second half to overturn a 1-0 deficit. The victory cements manager Carlo Ancelotti\'s status as the most decorated coach in Champions League history.',
    source: 'Sky Sports',
    sourceLogo: '⚽',
    category: 'sports',
    imageUrl: 'https://picsum.photos/seed/ucl/800/450',
    publishedAt: new Date(now - 8 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '10',
    title: 'Fed Signals Potential Rate Cut Amid Cooling Inflation Data',
    summary: 'Federal Reserve officials hint at policy easing as consumer price index falls to lowest level in two years.',
    fullContent: 'The Federal Reserve has signaled that it may begin cutting interest rates as early as next quarter, following the release of new inflation data showing the consumer price index has dropped to 2.1%, its lowest level since early 2024. Fed Chair Jerome Powell stated that the committee is increasingly confident that inflation is sustainably moving toward the 2% target.',
    source: 'CNBC',
    sourceLogo: '🏦',
    category: 'business',
    imageUrl: 'https://picsum.photos/seed/fed/800/450',
    publishedAt: new Date(now - 10 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '11',
    title: 'Breakthrough Gene Therapy Shows Promise in Treating Rare Childhood Disease',
    summary: 'Clinical trials demonstrate 95% success rate in reversing symptoms of spinal muscular atrophy.',
    fullContent: 'Researchers at Boston Children\'s Hospital have published results from a groundbreaking gene therapy trial that shows a 95% success rate in treating spinal muscular atrophy (SMA) in infants. The therapy, which delivers a functional copy of the SMN1 gene, has allowed previously paralyzed children to walk and breathe independently.',
    source: 'Science Daily',
    sourceLogo: '🧬',
    category: 'science',
    imageUrl: 'https://picsum.photos/seed/gene/800/450',
    publishedAt: new Date(now - 12 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '12',
    title: 'Japan Earthquake Triggers Tsunami Warning for Pacific Coast',
    summary: 'A 7.8 magnitude quake off the coast of Hokkaido prompts evacuations across coastal communities.',
    fullContent: 'A powerful 7.8 magnitude earthquake struck off the coast of Hokkaido, Japan, triggering tsunami warnings across the Pacific region. Coastal communities have been evacuated as waves up to 3 meters are expected. The Japan Meteorological Agency has issued its highest-level alert, and emergency services are on standby.',
    source: 'NHK World',
    sourceLogo: '🌊',
    category: 'world',
    imageUrl: 'https://picsum.photos/seed/quake/800/450',
    publishedAt: new Date(now - 14 * hr).toISOString(),
    url: '#',
    isLive: true,
    isNew: false,
  },
  {
    id: '13',
    title: 'Tesla Unveils Affordable $25,000 Electric Vehicle for Mass Market',
    summary: 'The new compact EV aims to make electric transportation accessible to the average consumer.',
    fullContent: 'Tesla has officially revealed its highly anticipated $25,000 electric vehicle at a special event in Austin, Texas. The compact hatchback features a 300-mile range, fast charging capability, and includes Tesla\'s full self-driving hardware. Production is expected to begin at the Gigafactory in Texas within six months.',
    source: 'Electrek',
    sourceLogo: '🚗',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/tesla/800/450',
    publishedAt: new Date(now - 16 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '14',
    title: 'Olympic Committee Announces 2036 Games Host City',
    summary: 'After months of deliberation, the IOC has selected the host city for the Summer Olympics.',
    fullContent: 'The International Olympic Committee has announced that Istanbul, Turkey will host the 2036 Summer Olympics. The city beat out competing bids from Madrid and Mumbai. The games are expected to generate over $12 billion in economic activity and will feature several new sports disciplines.',
    source: 'AP News',
    sourceLogo: '🏅',
    category: 'sports',
    imageUrl: 'https://picsum.photos/seed/olympics/800/450',
    publishedAt: new Date(now - 18 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '15',
    title: 'India Overtakes China as World\'s Largest Economy by GDP',
    summary: 'Rapid digital transformation and a booming tech sector drive India to the top spot.',
    fullContent: 'India has officially surpassed China to become the world\'s largest economy by GDP, driven by explosive growth in its technology sector and a rapidly expanding middle class. The World Bank confirmed the milestone, noting India\'s GDP now exceeds $4.2 trillion. Economists project continued strong growth through the end of the decade.',
    source: 'Financial Times',
    sourceLogo: '📈',
    category: 'business',
    imageUrl: 'https://picsum.photos/seed/india-gdp/800/450',
    publishedAt: new Date(now - 20 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '16',
    title: 'Climate Summit Produces Historic Agreement on Carbon Emissions',
    summary: 'Nearly 200 nations commit to 60% emission reduction by 2035 in landmark deal.',
    fullContent: 'In a historic breakthrough, representatives from nearly 200 countries have agreed to cut carbon emissions by 60% by 2035 at the UN Climate Change Conference. The agreement includes a $500 billion annual fund for developing nations to transition to renewable energy. Scientists hailed the deal as a critical step in preventing the worst impacts of climate change.',
    source: 'BBC News',
    sourceLogo: '🌍',
    category: 'world',
    imageUrl: 'https://picsum.photos/seed/climate/800/450',
    publishedAt: new Date(now - 22 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '17',
    title: 'Quantum Computer Achieves New Milestone in Error Correction',
    summary: 'IBM\'s latest quantum processor demonstrates fault-tolerant computation for the first time at scale.',
    fullContent: 'IBM has announced a major breakthrough in quantum computing with its latest 1,121-qubit processor achieving fault-tolerant quantum computation at scale. The system demonstrated reliable error correction across hundreds of logical qubits, bringing practical quantum computing closer to reality. IBM expects to make the system available to researchers through its cloud platform.',
    source: 'MIT Technology Review',
    sourceLogo: '💻',
    category: 'tech',
    imageUrl: 'https://picsum.photos/seed/quantum/800/450',
    publishedAt: new Date(now - 1 * 24 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '18',
    title: 'Premier League Season Opener Delivers Five-Goal Thriller',
    summary: 'Manchester United and Liverpool share the spoils in an electrifying start to the new campaign.',
    fullContent: 'The English Premier League kicked off its new season with a classic encounter between Manchester United and Liverpool, ending 3-2 in favor of the home side. The match featured stunning goals, a penalty controversy, and a dramatic late winner that sent Old Trafford into raptures.',
    source: 'Sky Sports',
    sourceLogo: '⚽',
    category: 'sports',
    imageUrl: 'https://picsum.photos/seed/epl/800/450',
    publishedAt: new Date(now - 1.2 * 24 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '19',
    title: 'New Study Links Sleep Quality to Long-Term Brain Health',
    summary: 'Researchers find consistent deep sleep patterns reduce dementia risk by up to 40%.',
    fullContent: 'A comprehensive 15-year study published in The Lancet has found that consistent deep sleep patterns are strongly correlated with reduced risk of cognitive decline and dementia. Participants who averaged 7-8 hours of quality sleep showed a 40% lower risk of developing Alzheimer\'s disease. The findings suggest sleep interventions could be a powerful preventive tool.',
    source: 'The Lancet',
    sourceLogo: '🧠',
    category: 'science',
    imageUrl: 'https://picsum.photos/seed/sleep/800/450',
    publishedAt: new Date(now - 1.5 * 24 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '20',
    title: 'Oil Prices Surge Past $100 Amid Middle East Supply Concerns',
    summary: 'Geopolitical tensions in the Gulf region threaten to disrupt global energy supplies.',
    fullContent: 'Crude oil prices have surged above $100 per barrel for the first time in two years as escalating tensions in the Middle East raise concerns about supply disruptions. OPEC members have called an emergency meeting to discuss production levels. Analysts warn that sustained high energy prices could reignite inflation globally.',
    source: 'Wall Street Journal',
    sourceLogo: '🛢️',
    category: 'business',
    imageUrl: 'https://picsum.photos/seed/oil/800/450',
    publishedAt: new Date(now - 1.8 * 24 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '21',
    title: 'Ceasefire Negotiations Resume in Eastern Europe After Intense Fighting',
    summary: 'Diplomats from both sides meet in Geneva for fresh talks as humanitarian corridors are established.',
    fullContent: 'After weeks of intense fighting, representatives from both nations have gathered in Geneva for renewed ceasefire negotiations. The talks come after international pressure and the establishment of humanitarian corridors allowing civilians to evacuate conflict zones. UN Secretary-General called the talks a "critical window of opportunity" for peace.',
    source: 'Al Jazeera',
    sourceLogo: '🕊️',
    category: 'war',
    imageUrl: 'https://picsum.photos/seed/ceasefire/800/450',
    publishedAt: new Date(now - 30 * min).toISOString(),
    url: '#',
    isLive: true,
    isNew: true,
  },
  {
    id: '22',
    title: 'UN Peacekeepers Deployed to Stabilize Tensions in Central Africa',
    summary: 'A new multinational force arrives as displaced populations seek safe refuge.',
    fullContent: 'The United Nations has deployed 5,000 peacekeepers to the Central African region following escalating tensions between rival factions. The deployment aims to protect civilians, facilitate humanitarian aid, and create conditions for political dialogue. Aid agencies report over 200,000 people have been displaced in recent weeks.',
    source: 'Reuters',
    sourceLogo: '🏛️',
    category: 'war',
    imageUrl: 'https://picsum.photos/seed/peacekeepers/800/450',
    publishedAt: new Date(now - 3 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '23',
    title: 'Military Analysts Warn of Escalation in South China Sea Dispute',
    summary: 'Naval deployments increase as territorial claims intensify between multiple nations.',
    fullContent: 'Defense analysts are raising concerns about an escalation in the South China Sea, where multiple nations have increased naval deployments amid disputed territorial claims. Satellite imagery shows several warships positioned near contested islands. Diplomatic channels remain active but tensions continue to rise.',
    source: 'Defense One',
    sourceLogo: '⚓',
    category: 'war',
    imageUrl: 'https://picsum.photos/seed/naval/800/450',
    publishedAt: new Date(now - 6 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '24',
    title: 'Revolutionary mRNA Vaccine Shows 97% Efficacy Against Aggressive Cancer',
    summary: 'Phase 3 trials confirm breakthrough treatment could transform oncology within five years.',
    fullContent: 'A groundbreaking mRNA-based cancer vaccine has demonstrated 97% efficacy in Phase 3 clinical trials against an aggressive form of lung cancer. The treatment, developed by BioNTech and Moderna in collaboration, trains the immune system to target tumor-specific mutations. Researchers call it the most significant advance in cancer treatment in decades.',
    source: 'Nature Medicine',
    sourceLogo: '💉',
    category: 'health',
    imageUrl: 'https://picsum.photos/seed/mrna/800/450',
    publishedAt: new Date(now - 1 * hr).toISOString(),
    url: '#',
    isLive: true,
    isNew: true,
  },
  {
    id: '25',
    title: 'WHO Declares End of Global Mental Health Emergency Framework',
    summary: 'New international guidelines aim to integrate mental health into primary care worldwide.',
    fullContent: 'The World Health Organization has introduced a comprehensive global mental health framework, calling for the integration of mental health services into primary healthcare systems worldwide. The initiative aims to provide affordable mental health support in 150 countries by 2030, addressing what the WHO calls a "hidden pandemic" of anxiety and depression.',
    source: 'BBC Health',
    sourceLogo: '🏥',
    category: 'health',
    imageUrl: 'https://picsum.photos/seed/mental-health/800/450',
    publishedAt: new Date(now - 4 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '26',
    title: 'Breakthrough Alzheimer\'s Drug Slows Cognitive Decline by 60% in Trials',
    summary: 'Leqembi successor shows dramatic results in preserving memory and daily function.',
    fullContent: 'A next-generation Alzheimer\'s drug has shown remarkable results in clinical trials, slowing cognitive decline by 60% compared to placebo. The drug targets amyloid plaques while also reducing neuroinflammation. The FDA is expected to fast-track review, potentially making it available to patients by early next year.',
    source: 'The Lancet',
    sourceLogo: '🧠',
    category: 'health',
    imageUrl: 'https://picsum.photos/seed/alzheimer/800/450',
    publishedAt: new Date(now - 8 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '27',
    title: 'Marvel Announces Phase 7 Lineup Including X-Men Reboot',
    summary: 'Studio reveals 12 new films and series at San Diego Comic-Con, fans react with excitement.',
    fullContent: 'Marvel Studios unveiled its Phase 7 slate at San Diego Comic-Con, headlined by a full X-Men reboot featuring an entirely new cast. The lineup includes 12 films and 8 Disney+ series spanning 2027-2029. The announcement drew massive cheers from the audience, with Kevin Feige promising a "bold new direction" for the franchise.',
    source: 'Variety',
    sourceLogo: '🎬',
    category: 'entertainment',
    imageUrl: 'https://picsum.photos/seed/marvel/800/450',
    publishedAt: new Date(now - 2 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: true,
  },
  {
    id: '28',
    title: 'Streaming Wars Intensify as Netflix Acquires Major Gaming Studio',
    summary: 'The $4.2 billion deal signals a major push into interactive entertainment.',
    fullContent: 'Netflix has announced the acquisition of a leading video game studio for $4.2 billion, its largest gaming investment to date. The move is part of the streaming giant\'s strategy to expand beyond passive viewing into interactive entertainment. Analysts predict the deal will reshape the competitive landscape between streaming platforms.',
    source: 'The Verge',
    sourceLogo: '🎮',
    category: 'entertainment',
    imageUrl: 'https://picsum.photos/seed/netflix-gaming/800/450',
    publishedAt: new Date(now - 5 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '29',
    title: 'BTS Announces Global Reunion Tour After Military Service',
    summary: 'K-pop supergroup confirms 60-city world tour kicking off in Seoul next spring.',
    fullContent: 'K-pop sensation BTS has officially announced their highly anticipated reunion world tour, set to begin in Seoul next spring. The 60-city tour will span six continents and is expected to break attendance records. All seven members will participate following the completion of their mandatory military service.',
    source: 'Rolling Stone',
    sourceLogo: '🎵',
    category: 'entertainment',
    imageUrl: 'https://picsum.photos/seed/bts/800/450',
    publishedAt: new Date(now - 10 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '30',
    title: 'Supreme Court Issues Landmark Ruling on Digital Privacy Rights',
    summary: 'Justices rule 6-3 that law enforcement needs a warrant for all digital data access.',
    fullContent: 'The U.S. Supreme Court has issued a landmark 6-3 ruling expanding digital privacy protections, requiring law enforcement to obtain a warrant before accessing any digital data, including cloud storage and encrypted messages. Civil liberties groups hailed the decision as a critical update to Fourth Amendment protections in the digital age.',
    source: 'Politico',
    sourceLogo: '⚖️',
    category: 'politics',
    imageUrl: 'https://picsum.photos/seed/scotus/800/450',
    publishedAt: new Date(now - 45 * min).toISOString(),
    url: '#',
    isLive: true,
    isNew: true,
  },
  {
    id: '31',
    title: 'President Signs Executive Order on AI Safety and Regulation',
    summary: 'New executive directive mandates safety testing for all advanced AI systems before deployment.',
    fullContent: 'The President has signed a sweeping executive order on artificial intelligence safety, requiring all advanced AI systems to undergo mandatory safety testing before public deployment. The order also establishes a new federal AI Safety Board and allocates $2 billion for AI safety research. Tech industry leaders have expressed cautious support for the framework.',
    source: 'Washington Post',
    sourceLogo: '🏛️',
    category: 'politics',
    imageUrl: 'https://picsum.photos/seed/ai-exec/800/450',
    publishedAt: new Date(now - 7 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '32',
    title: 'Global Elections 2026: Key Races to Watch Across Three Continents',
    summary: 'A record year for democracy as 40+ nations hold elections, shaping global policy.',
    fullContent: '2026 is shaping up to be a historic year for elections worldwide, with over 40 nations scheduled to hold national votes across Europe, Asia, and South America. Analysts say the outcomes could dramatically shift global policy on climate, trade, and technology regulation. Key races include elections in Germany, Brazil, and India.',
    source: 'The Economist',
    sourceLogo: '🗳️',
    category: 'politics',
    imageUrl: 'https://picsum.photos/seed/elections/800/450',
    publishedAt: new Date(now - 12 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '33',
    title: 'Arctic Ice Sheet Loss Accelerates Beyond Worst-Case Projections',
    summary: 'New satellite data shows ice loss 30% faster than climate models predicted.',
    fullContent: 'Scientists have reported alarming new data showing that the Arctic ice sheet is deteriorating 30% faster than the worst-case climate models predicted. The findings, published in Nature Climate Change, suggest sea levels could rise by over 1 meter by 2050, threatening coastal cities worldwide.',
    source: 'Nature Climate Change',
    sourceLogo: '🧊',
    category: 'climate',
    imageUrl: 'https://picsum.photos/seed/arctic/800/450',
    publishedAt: new Date(now - 2 * hr).toISOString(),
    url: '#',
    isLive: true,
    isNew: true,
  },
  {
    id: '34',
    title: 'Massive Reforestation Project Restores 10 Million Hectares in Amazon',
    summary: 'International coalition celebrates the largest ecosystem restoration in history.',
    fullContent: 'A multinational reforestation effort has successfully restored 10 million hectares of the Amazon rainforest, marking the largest ecosystem restoration project in human history. The initiative, funded by 20 nations and private donors, has already shown measurable improvements in regional rainfall patterns and biodiversity.',
    source: 'National Geographic',
    sourceLogo: '🌳',
    category: 'climate',
    imageUrl: 'https://picsum.photos/seed/amazon/800/450',
    publishedAt: new Date(now - 9 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
  {
    id: '35',
    title: 'Renewable Energy Surpasses Fossil Fuels in Global Electricity Generation',
    summary: 'Solar and wind now provide more electricity than coal and gas combined worldwide.',
    fullContent: 'In a historic milestone, renewable energy sources have surpassed fossil fuels in global electricity generation for the first time. Solar and wind combined now provide more power than coal and natural gas worldwide. The International Energy Agency called the achievement a "tipping point" in the clean energy transition.',
    source: 'Bloomberg Green',
    sourceLogo: '⚡',
    category: 'climate',
    imageUrl: 'https://picsum.photos/seed/renewable/800/450',
    publishedAt: new Date(now - 15 * hr).toISOString(),
    url: '#',
    isLive: false,
    isNew: false,
  },
];

export const trendingTopics = [
  { topic: '#CeasefireNow', count: '156K posts' },
  { topic: '#MRNACancer', count: '112K posts' },
  { topic: '#GPT5', count: '98K posts' },
  { topic: '#ClimateTipping', count: '87K posts' },
  { topic: '#SCOTUSRuling', count: '64K posts' },
];

export const topSources = [
  { name: 'TechCrunch', articles: 342 },
  { name: 'Reuters', articles: 289 },
  { name: 'ESPN', articles: 256 },
  { name: 'Bloomberg', articles: 231 },
  { name: 'Nature', articles: 198 },
];
